// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPTTzE7hWz2EXFStWgZMKpIzQq2xYiBc',
    appId: '1:991150442798:web:31230dd17e08b7c73fd2bf',
    messagingSenderId: '991150442798',
    projectId: 'digital-twin-36434',
    authDomain: 'digital-twin-36434.firebaseapp.com',
    storageBucket: 'digital-twin-36434.firebasestorage.app',
    measurementId: 'G-NY5HENVX0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6yyOdffeKAT__jleODtLUZK2tXpRxN8',
    appId: '1:991150442798:android:b6107db4766ceca73fd2bf',
    messagingSenderId: '991150442798',
    projectId: 'digital-twin-36434',
    storageBucket: 'digital-twin-36434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPOM3RoDx9-ihwarNFl9Hxk5AB9JKEPY',
    appId: '1:991150442798:ios:30c122e75acbd8db3fd2bf',
    messagingSenderId: '991150442798',
    projectId: 'digital-twin-36434',
    storageBucket: 'digital-twin-36434.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqPOM3RoDx9-ihwarNFl9Hxk5AB9JKEPY',
    appId: '1:991150442798:ios:30c122e75acbd8db3fd2bf',
    messagingSenderId: '991150442798',
    projectId: 'digital-twin-36434',
    storageBucket: 'digital-twin-36434.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmPTTzE7hWz2EXFStWgZMKpIzQq2xYiBc',
    appId: '1:991150442798:web:c261b9fa2d112bcf3fd2bf',
    messagingSenderId: '991150442798',
    projectId: 'digital-twin-36434',
    authDomain: 'digital-twin-36434.firebaseapp.com',
    storageBucket: 'digital-twin-36434.firebasestorage.app',
    measurementId: 'G-VFC7KW31TF',
  );
}
